[tool.black]
# target-version = ['py39', 'py310']
line-length = 88
exclude = '''
^/(
  (
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | venv
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 88

[tool.mypy]
# python_version = "3.9"
warn_return_any = true
follow_imports = "skip"
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_configs = true
show_column_numbers = true
ignore_errors = false
# disallow subclassing any false to not bother
# when an installed library doesn't have type info
disallow_subclassing_any = false
disallow_any_generics = true
# disallow untyped defs false to not bother
# with __init__ methods missing -> None
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
# disallow untyped decorators false to not bother
# when an installed library doesn't have type info in decorators
disallow_untyped_decorators = false
no_implicit_optional = true
warn_unused_ignores = true
no_implicit_reexport = false

# https://mypy.readthedocs.io/en/stable/config_file.html
